#! /usr/bin/env python2
# vim:fileencoding=utf-8
#
# Copyright © 2012-2014 R.F. Smith <rsmith@xs4all.nl>. All rights reserved.
# $Date$
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

"""Program for converting an STL file into a POV-ray mesh or mesh2."""

import argparse
import sys
import time
from stltools import stl, utils

__version__ = '$Revision$'[11:-2]


def mesh1(name, vertices, file):
    """Creates a POV-ray mesh description from facet data.

    :name: The name of the object.
    :vertices: An (N,3) numpy array containing the vertex data.
    :file: file object to write to.
    """
    facets = vertices.reshape((-1, 3, 3))
    file.write("# declare m_{} = mesh {{\n".format(name.replace(' ', '_')))
    sot = "  triangle {"
    # The indices sequence 1, 0, 2 is used because of the difference between
    # the STL coordinate system and that used in POV-ray.
    fc = "    <{1}, {0}, {2}>,"
    for (a, b, c) in facets:
        line = '\n'.join([sot, fc.format(*a), fc.format(*b),
                          fc.format(*c)[:-1], "  }\n"])
        file.write(line)


def mesh2(name, vertices, file):
    """Creates a POV-ray mesh2 object from facet data.

    :name: The name of the object.
    :vertices: An (N,3) numpy array containing the vertex data.
    :file: file object to write to.
    """
    ifacets, points = stl.toindexed(vertices)
    lines = ["# declare m_{} = mesh2 {{".format(name),
             '  vertex_vectors {', '    {}\n,'.format(len(points))]
    file.write('\n'.join(lines))
    # The indices sequence 1, 0, 2 is used because of the difference between
    # the STL coordinate system and that used in POV-ray
    for p in points[:-1]:
        file.write('    <{1}, {0}, {2}>,\n'.format(*p))
    p = points[-1]
    file.write('    <{1}, {0}, {2}>\n'.format(*p))
    file.write("  }\n")
    lines = ['  face_indices {', '    {},'.format(len(ifacets))]
    file.write('\n'.join(lines))
    for f in ifacets[:-1]:
        file.write('    <{}, {}, {}>,\n'.format(*f))
    lines = ['  }', '}\n']
    file.write('\n'.join(lines))


def main(argv):
    """Main program.

    :argv: command line arguments (without program name!)
    """
    msg = utils.Msg()
    parser = argparse.ArgumentParser(description=__doc__)
    argtxt = 'generate a mesh2 object (slow on big files)'
    parser.add_argument('-2,' '--mesh2', action='store_true',
                        help=argtxt, dest='mesh2')
    parser.add_argument('-v', '--version', action='version',
                        version=__version__)
    parser.add_argument('file', nargs='*', help='one or more file names')
    args = parser.parse_args(argv)
    if not args.file:
        parser.print_help()
        sys.exit(0)
    for fn in args.file:
        msg.say('Starting file "{}"'.format(fn))
        if not fn.lower().endswith('.stl'):
            w = 'The file "{}" is probably not an STL file, skipping.'
            msg.say(w.format(fn))
            continue
        try:
            msg.say('Reading facets')
            vertices, name = stl.readstl(fn)
            outfn = utils.outname(fn, '.inc')
        except Exception as e:  # pylint: disable=W0703
            msg.say('Error;', e)
            continue
        with open(outfn, 'w+') as of:
            outs = "// Generated by stl2pov {}\n".format(__version__)
            of.write(outs)
            outs = "// on {}.\n".format(time.asctime())
            of.write(outs)
            outs = "// Source file name: '{}'\n".format(fn)
            of.write(outs)
            if args.mesh2:
                msg.say('Writing mesh2 data')
                mesh2(name, vertices, of)
            else:
                msg.say('Writing mesh data')
                mesh1(name, vertices, of)
        msg.say('Done with file "{}"'.format(fn))


if __name__ == '__main__':
    main(sys.argv[1:])
