#!/bin/sh
# vim:fileencoding=utf-8
# Shell script to generate a full backup of the current directory.
#
# Author: R.F. Smith <rsmith@xs4all.nl>
# Created: 2013-08-13 22:13:23 +0200
# Modified: $Date: 2013-08-19 21:28:44 +0200 $
#
# To the extent possible under law, R.F. Smith has waived all copyright and
# related or neighboring rights to genbackup. This work is published 
# from the Netherlands. See http://creativecommons.org/publicdomain/zero/1.0/ 

# The base of the name is the last part of the current directory.
NAME=$(pwd)
DIR=$(basename $NAME)
NAME=$(echo $DIR|sed 's/^\./dot/')
# Add the short hashtag if the current directory is revision control by git.
if [ -d .git ]; then
    NUM=-$(git log -n 1 --oneline |cut -c 1-7)
else
    NUM=''
fi
# Use tar for backup. Standard compression with gzip.
DF=backup-${NAME}${NUM}.tar.gz
echo "A copy of ${DIR} is stored in ${DF}."
cd .. ; tar czf /tmp/${DF} ${DIR}/
mv /tmp/${DF} ${DIR}/
